[env:nodemcuv2]
platform = espressif8266@4.2.1
board = nodemcuv2
framework = arduino
monitor_speed = 115200
build_flags =
  -Wall
  -Wextra
lib_deps =
  dancol90/ESP8266Ping@^1.0
  bblanchon/ArduinoJson@^6.21.5
